# Generated by Django 5.1.3 on 2024-12-09 14:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=25, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=25, null=True, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('avatar', models.ImageField(default='avatars/default.jpg', null=True, upload_to='avatars/', verbose_name='Фото')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Доступ к админке')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('account_type', models.CharField(choices=[('SELLER', 'SELLER'), ('BUYER', 'BUYER')], max_length=6, verbose_name='Тип аккаунта')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
